server {
    listen ${PORT}; # Railway inyectará el puerto aquí
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Esto arregla el error de React Router
    }
}